export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_GET_ITEMS = "CART_GET_ITEMS";
export const CART_REMOVE_ONE_ITEM = "CART_REMOVE_ONE_ITEM";
export const CART_ALL_ITEMS_REMOVE = "CART_ALL_ITEMS_REMOVE";
