// delivery date constants
export const DATE_ADD_ITEM = "DATE_ADD_ITEM";
export const DATE_REMOVE_ITEM = "DATE_REMOVE_ITEM";
export const DATE_GET_ITEMS = "DATE_GET_ITEMS";
export const DATE_REMOVE_ONE_ITEM = "DATE_REMOVE_ONE_ITEM";
export const DATE_ALL_ITEMS_REMOVE = "DATE_ALL_ITEMS_REMOVE";
export const DATE_LIST_REQUEST = "DATE_LIST_REQUEST";
export const DATE_LIST_SUCCESS = "DATE_LIST_SUCCESS";
export const DATE_LIST_FAIL = "DATE_LIST_FAIL";
export const DELIVERY_DATE_RESET = "DELIVERY_DATE_RESET";

// delivery time constants
export const TIME_ADD_ITEM = "TIME_ADD_ITEM";
export const TIME_REMOVE_ITEM = "TIME_REMOVE_ITEM";
export const TIME_GET_ITEMS = "TIME_GET_ITEMS";
export const TIME_REMOVE_ONE_ITEM = "TIME_REMOVE_ONE_ITEM";
export const TIME_ALL_ITEMS_REMOVE = "TIME_ALL_ITEMS_REMOVE";
export const DELIVERYSCHEDULE_LIST_REQUEST = "DELIVERYSCHEDULE_LIST_REQUEST";
export const DELIVERYSCHEDULE_LIST_SUCCESS = "DELIVERYSCHEDULE_LIST_SUCCESS";
export const DELIVERYSCHEDULE_LIST_FAIL = "DELIVERYSCHEDULE_LIST_FAIL";
export const DELIVERY_TIME_RESET = "DELIVERY_TIME_RESET";