export const FREQUENTLY_LIST_REQUEST = "FREQUENTLY_LIST_REQUEST";
export const FREQUENTLY_LIST_SUCCESS = "FREQUENTLY_LIST_SUCCESS";
export const FREQUENTLY_LIST_FAIL = "FREQUENTLY_LIST_FAIL";
export const FREQUENTLY_ADD_ITEM = "FREQUENTLY_ADD_ITEM";
export const FREQUENTLY_GET_ITEMS = "FREQUENTLY_GET_ITEMS";
export const FREQUENTLY_REMOVE_ITEM = "FREQUENTLY_REMOVE_ITEM";
export const FREQUENTLY_REMOVE_ONE_ITEM = "FREQUENTLY_REMOVE_ONE_ITEM";
export const FREQUENTLY_ALL_ITEMS_REMOVE = "FREQUENTLY_ALL_ITEMS_REMOVE";
export const FREQUENTLY_LIST_RESET = "FREQUENTLY_LIST_RESET";

export const ALL_FREQUENTLY_GET_ITEMS = "ALL_FREQUENTLY_GET_ITEMS";
export const ALL_FREQUENTLY_ALL_ITEMS_REMOVE = "ALL_FREQUENTLY_ALL_ITEMS_REMOVE";
export const ALL_FREQUENTLY_LIST_REQUEST = "ALL_FREQUENTLY_LIST_REQUEST";
export const ALL_FREQUENTLY_LIST_FAIL = "ALL_FREQUENTLY_LIST_FAIL";
export const ALL_FREQUENTLY_LIST_SUCCESS = "ALL_FREQUENTLY_LIST_SUCCESS";
export const ALL_FREQUENTLY_LIST_RESET = "ALL_FREQUENTLY_LIST_RESET";

export const FREQUENTLY_DATETIME_LIST_REQUEST = "FREQUENTLY_DATETIME_LIST_REQUEST";
export const FREQUENTLY_DATETIME_LIST_SUCCESS = "FREQUENTLY_DATETIME_LIST_SUCCESS";
export const FREQUENTLY_DATETIME_LIST_FAIL = "FREQUENTLY_DATETIME_LIST_FAIL";