export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAIL = "REVIEW_CREATE_FAIL";

export const REVIEW_DETAILS_REQUEST = "REVIEW_DETAILS_REQUEST";
export const REVIEW_DETAILS_SUCCESS = "REVIEW_DETAILS_SUCCESS";
export const REVIEW_DETAILS_FAIL = "REVIEW_DETAILS_FAIL";

export const REVIEW_PAY_REQUEST = "REVIEW_PAY_REQUEST";
export const REVIEW_PAY_SUCCESS = "REVIEW_PAY_SUCCESS";
export const REVIEW_PAY_FAIL = "REVIEW_PAY_FAIL";
export const REVIEW_PAY_RESET = "REVIEW_PAY_RESET";

export const REVIEW_LIST_MY_REQUEST = "REVIEW_LIST_MY_REQUEST";
export const REVIEW_LIST_MY_SUCCESS = "REVIEW_LIST_MY_SUCCESS";
export const REVIEW_LIST_MY_FAIL = "REVIEW_LIST_MY_FAIL";
export const REVIEW_LIST_MY_RESET = "REVIEW_LIST_MY_RESET";

export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const REVIEW_DELIVER_REQUEST = "REVIEW_DELIVER_REQUEST";
export const REVIEW_DELIVER_SUCCESS = "REVIEW_DELIVER_SUCCESS";
export const REVIEW_DELIVER_FAIL = "REVIEW_DELIVER_FAIL";
export const REVIEW_DELIVER_RESET = "REVIEW_DELIVER_RESET";
export const UPDATE_EACH_PSTAR_REQUEST = "UPDATE_EACH_PSTAR_REQUEST";
export const UPDATE_EACH_PSTAR_SUCCESS = "UPDATE_EACH_PSTAR_SUCCESS";
export const UPDATE_EACH_PSTAR_FAIL = "UPDATE_EACH_PSTAR_FAIL";
