export const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST";
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCTS_LIST_FAIL = "PRODUCTS_LIST_FAIL";

export const PRODUCTS_UPDATE_REQUEST = "PRODUCTS_UPDATE_REQUEST";
export const PRODUCTS_UPDATE_SUCCESS = "PRODUCTS_UPDATE_SUCCESS";
export const PRODUCTS_UPDATE_FAIL = "PRODUCTS_UPDATE_FAIL";
